# Generated by Django 3.1.3 on 2022-05-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[(2, 'Caucasian'), (0, 'AfricanAmerican'), (-1, 'Hispanic'), (3, 'Other'), (4, 'Asian'), (1, 'None')], max_length=20)),
                ('gender', models.CharField(choices=[(0, 'Male'), (1, 'Female')], max_length=7)),
                ('admission_type_id', models.IntegerField()),
                ('discharge_disposition_id', models.IntegerField()),
                ('admission_source_id', models.IntegerField()),
                ('time_in_hospital', models.IntegerField()),
                ('num_lab_procedures', models.IntegerField()),
                ('num_procedures', models.IntegerField()),
                ('num_medications', models.IntegerField()),
                ('number_outpatient', models.IntegerField()),
                ('number_emergency', models.IntegerField()),
                ('number_inpatient', models.IntegerField()),
                ('diag_1', models.IntegerField()),
                ('number_diagnoses', models.IntegerField()),
                ('max_glu_serum', models.CharField(choices=[(2, 'None'), (3, 'Norm'), (0, '>200'), (1, '>300')], max_length=5)),
                ('A1Cresult', models.CharField(choices=[(2, 'None'), (1, '>8'), (3, 'Norm'), (0, '>7')], max_length=5)),
                ('metformin', models.CharField(choices=[(1, 'No'), (2, 'Steady'), (3, 'Up'), (0, 'Down')], max_length=5)),
                ('repaglinide', models.CharField(choices=[(1, 'No'), (2, 'Steady'), (3, 'Up'), (0, 'Down')], max_length=5)),
                ('pioglitazone', models.CharField(choices=[(1, 'No'), (2, 'Steady'), (3, 'Up'), (0, 'Down')], max_length=5)),
                ('glipizide_metformin', models.CharField(choices=[(1, 'No'), (2, 'Steady'), (3, 'Up'), (0, 'Down')], max_length=5)),
                ('change', models.CharField(choices=[(1, 'No'), (0, 'Ch')], max_length=3)),
                ('diabetesMed', models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=3)),
            ],
        ),
    ]
