# Generated by Django 3.1.3 on 2022-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='A1Cresult',
            field=models.CharField(choices=[('2', 'None'), ('1', '>8'), ('3', 'Norm'), ('0', '>7')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='change',
            field=models.CharField(choices=[('1', 'No'), ('0', 'Ch')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='diabetesMed',
            field=models.CharField(choices=[('1', 'Yes'), ('0', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='glipizide_metformin',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Steady'), ('3', 'Up'), ('0', 'Down')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='max_glu_serum',
            field=models.CharField(choices=[('2', 'None'), ('3', 'Norm'), ('0', '>200'), ('1', '>300')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='metformin',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Steady'), ('3', 'Up'), ('0', 'Down')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='pioglitazone',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Steady'), ('3', 'Up'), ('0', 'Down')], max_length=1),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='race',
            field=models.CharField(choices=[('2', 'Caucasian'), ('0', 'AfricanAmerican'), ('-1', 'Hispanic'), ('3', 'Other'), ('4', 'Asian'), ('1', 'None')], max_length=2),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='repaglinide',
            field=models.CharField(choices=[('1', 'No'), ('2', 'Steady'), ('3', 'Up'), ('0', 'Down')], max_length=1),
        ),
    ]
