# Generated by Django 3.1.3 on 2022-05-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_auto_20220508_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='admission_type_id',
        ),
    ]
