# Generated by Django 3.1.3 on 2022-05-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_remove_datapoint_admission_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='diag_1',
            new_name='diag_3',
        ),
    ]
